## Tensorflow Denemeleri

Geçtiğimiz haftanın büyük bir bölümünde, Derin Öğrenme modellerinizde tensörler kullandınız. Bugünkü zorluklar boyunca, tensörleri kapsamlı bir şekilde kullanacak ve bazı alışılmadık model mimarileriyle çalışacaksınız. 


Bu ısınma çalışmasında, bazı yeni yöntemlerle tanışacaksınız. 

Buradaki tüm yöntemler, günün ilerleyen saatlerinde karşılaşacağınız zorlukları 100 kat daha kolay hale getirecek, bu nedenle daha sonra takılırsanız, doğru cevapları nasıl bulduğunuzu görmek için buraya geri dönün. 

In [1]:
import tensorflow as tf

2026-05-13 00:47:52.921812: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-05-13 00:47:52.922497: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2026-05-13 00:47:52.924686: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2026-05-13 00:47:52.931810: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:479] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-05-13 00:47:52.945139: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:10575] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registe

A) `tf.ones` kullanarak (3,3) şeklinde birler ile doldurulmuş bir tensör `a` oluşturun.

In [2]:
# (3,3) şeklinde, birlerden oluşan bir tensör oluşturma
a = tf.ones((3, 3))
print(a)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


2026-05-13 00:48:51.375435: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2026-05-13 00:48:51.376090: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2251] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


B) tf.expand_dims kullanarak `a`'yı `b` adlı (1,3,3) şekilli bir nesne haline getirin.

In [3]:
# a tensörüne yeni bir boyut ekleyerek (1, 3, 3) şekline getirme
b = tf.expand_dims(a, axis=0)
print(b)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 3, 3), dtype=float32)


C) Boyutu (9,1) olan ve sıfırlarla dolu bir tensör `c` oluşturun.

In [4]:
# (9,1) şeklinde, sıfırlardan oluşan bir tensör oluşturma
c = tf.zeros((9, 1))
print(c)

tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(9, 1), dtype=float32)


D) `c`'yi (1, 3, 3) şeklinde yeniden şekillendirin. Adını `d` olarak belirleyin.

In [5]:
# c tensörünü (1, 3, 3) şeklinde yeniden şekillendirme
d = tf.reshape(c, (1, 3, 3))
print(d)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(1, 3, 3), dtype=float32)


E) `tf.matmul` kullanarak `b` ve `d` matrislerini birbiriyle çarpın ve şimdi tensörü `e`'ye atayın. 

In [6]:
# b ve d matrislerini çarparak e tensörünü oluşturma
e = tf.matmul(b, d)
print(e)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(1, 3, 3), dtype=float32)


F) Aşağıda bir `numpy` dizisi bulunmaktadır. Bunu `array_tensor` adlı bir tensöre dönüştürün. Ardından `tf.cast` kullanarak bunun `int` değil `float` türü olduğundan emin olun. Sonucu `f`'ye atayın.

In [8]:
import numpy as np

In [9]:
array = np.array([[
    [1,2,3],
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])

In [10]:
# Numpy dizisini tensöre dönüştürme
array_tensor = tf.convert_to_tensor(array)

# Veri tipini float olarak değiştirme
f = tf.cast(array_tensor, dtype=tf.float32)

print(f)

tf.Tensor(
[[[1. 2. 3.]
  [1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]], shape=(1, 4, 3), dtype=float32)


G) `f`'nin __last column__ değerleri seçin ve bunu `g`'ye kaydedin. Açıkça belirtmek gerekirse, `g`'nin şekli (4,) olmalı ve `3,3,6,9` değerlerini içermelidir. 

In [11]:
# f tensöründen son sütundaki değerleri seçme
# Dilimleme: [tüm listeler, tüm satırlar, son sütun]
g = f[0, :, -1]

print(f"g tensörü: {g}")
print(f"Şekil (Shape): {g.shape}")

g tensörü: [3. 3. 6. 9.]
Şekil (Shape): (4,)


H) g boyutlarını (4,1) şekline gelecek şekilde genişletin. Bunu `h`'ye atayın.

In [12]:
# g tensörünün boyutunu (4, 1) olacak şekilde genişletme
h = tf.expand_dims(g, axis=-1)

print(f"h tensörü:\n{h}")
print(f"Şekil (Shape): {h.shape}")

h tensörü:
[[3.]
 [3.]
 [6.]
 [9.]]
Şekil (Shape): (4, 1)


I) İsteğe bağlı `transpose_b` argümanıyla `tf.matmul` kullanarak e ile f'yi çarpın (konumsal argümanlarınızda önce `e`, sonra `f` gelmelidir). Bunu `i`'ye atayın.

In [13]:
# e ve f matrislerini f'nin transpozunu alarak çarpma
i = tf.matmul(e, f, transpose_b=True)

print(f"i tensörü:\n{i}")
print(f"Şekil (Shape): {i.shape}")

i tensörü:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
Şekil (Shape): (1, 3, 4)


J) Birlerle dolu bir `(10,10)` tensör oluşturun. Ardından `tf.linalg.band_part()` kullanarak matrisin üst üçgenini maskeleme yapın (yani üst üçgenin tamamı 0 olmalıdır). `j`'ye atayın.

In [14]:
# (10,10) boyutunda birlerden oluşan tensör oluşturma
ones_tensor = tf.ones((10, 10))

# tf.linalg.band_part(input, num_lower, num_upper)
# num_upper = 0 yaparak üst üçgeni sıfırlıyoruz (maskeleme)
j = tf.linalg.band_part(ones_tensor, num_lower=-1, num_upper=0)

print(j)

tf.Tensor(
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(10, 10), dtype=float32)


K) Aşağıdaki `number_list`'i alın ve bir tensör haline getirin. Bunu `k`'ye atayın.

In [15]:
number_list = [1,2,3,4,8]

In [16]:
# Liste verisini TensorFlow tensörüne dönüştürme
k = tf.convert_to_tensor(number_list)

print(k)

tf.Tensor([1 2 3 4 8], shape=(5,), dtype=int32)


L) `tf.expand_dims` kullanarak `k`'yi (1,5) şekilli bir tensör haline getirin. `l`'ye atayın.

In [17]:
# k tensörünün boyutunu (1, 5) olacak şekilde genişletme
l = tf.expand_dims(k, axis=0)

print(f"l tensörü: {l}")
print(f"Şekil (Shape): {l.shape}")

l tensörü: [[1 2 3 4 8]]
Şekil (Shape): (1, 5)


M) `tf.tile` kullanarak `l` (okunuşu “L”) 50 kez tekrarlayın, sonuçta `(50, 5)` şeklinde olsun. `m`'ye atayın.

In [18]:
# l tensörünü satır bazında 50 kez tekrarlayarak (50, 5) şekline getirme
# multiples=[50, 1] -> 0. boyutu 50 kez, 1. boyutu 1 kez tekrarla
m = tf.tile(l, multiples=[50, 1])

print(f"m tensörünün şekli (Shape): {m.shape}")
print(m)

m tensörünün şekli (Shape): (50, 5)
tf.Tensor(
[[1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]], shape=(50, 5), dtype=int32)


N) Basit bir Boolean ifadesi kullanarak, `m`'nin 3 olduğu yerler için `True` değerleri ve 3 olmadığı yerler için `False` değerleri içeren bir tensör oluşturun. `n`'ye atayın.

In [19]:
# m tensöründeki değerlerin 3'e eşit olup olmadığını kontrol etme
n = (m == 3)

print(n)

tf.Tensor(
[[False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]

O) Değişkeniniz `m` içindeki her değeri 3'e bölün. `o`'ya atayın.

In [20]:
# m tensöründeki her değeri 3'e bölme
o = m / 3

print(o)

tf.Tensor(
[[0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0

P) `tf.concat()` kullanarak, aşağıdaki (5,5) ve (5,5) şekilli iki tensörün listesini alın ve bunları (10,5) şekilli son bir tensöre dönüştürün. `p`'ye atayın. Birleştirme eksenini dikkatlice düşünün.

In [ ]:
tensor_list = [tf.ones((5,5)), tf.ones((5,5))]

In [21]:
tensor_list = [tf.ones((5,5)), tf.ones((5,5))]

# İki (5,5) tensörünü (10,5) yapmak için satır bazında (axis=0) birleştirme
p = tf.concat(tensor_list, axis=0)

print(f"p tensörünün şekli (Shape): {p.shape}")
print(p)

p tensörünün şekli (Shape): (10, 5)
tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(10, 5), dtype=float32)


### Cevaplarını Kontrol Et

In [22]:
from nbresult import ChallengeResult

result = ChallengeResult(
    "tensors",
    a=a.numpy(),
    b=b.numpy(),
    c=c.numpy(),
    d_shape=tuple(d.shape),
    e=e.numpy(),
    f=f.numpy(),
    g=g.numpy(),
    h=h.numpy(),
    i=i.numpy(),
    j=j.numpy(),
    k=k.numpy(),
    l=l.numpy(),
    m=m.numpy(),
    n=n.numpy(),
    o=o.numpy(),
    p_shape=tuple(p.shape),
)

result.write()
print(result.check())


============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/semih/.pyenv/versions/3.12.9/envs/workintech/bin/python
cachedir: .pytest_cache
rootdir: /home/semih/code/Semih0799/S19D2-S-Data-tensor-trials/tests
plugins: anyio-4.8.0, typeguard-4.4.2
collecting ... collected 15 items

test_tensors.py::TestTensors::test_a PASSED                              [  6%]
test_tensors.py::TestTensors::test_b PASSED                              [ 13%]
test_tensors.py::TestTensors::test_c PASSED                              [ 20%]
test_tensors.py::TestTensors::test_d_shape PASSED                        [ 26%]
test_tensors.py::TestTensors::test_e PASSED                              [ 33%]
test_tensors.py::TestTensors::test_f PASSED                              [ 40%]
test_tensors.py::TestTensors::test_g PASSED                              [ 46%]
test_tensors.py::TestTensors::test_i PASSED                        

### Harika iş 🔥

Şimdi modellemeye başlama zamanı!